Update azure-static-web-apps-lively-pebble-0a653070f.yml

diff --git a/.github/workflows/azure-static-web-apps-lively-pebble-0a653070f.yml b/.github/workflows/azure-static-web-apps-lively-pebble-0a653070f.yml
--- a/.github/workflows/azure-static-web-apps-lively-pebble-0a653070f.yml
+++ b/.github/workflows/azure-static-web-apps-lively-pebble-0a653070f.yml
@@ -33,8 +33,7 @@ jobs:
           ###### End of Repository/Build Configurations ######
       - name: Manually Unset the Extra Header
            # This step attempts to preempt the cleanup
-        run: | 
-        /usr/bin/git config --local --unset-all http.https://github.com/.extraheader || echo "Header not found or failed to remove (expected if cleanup runs next)"
+        run: /usr/bin/git config --local --unset-all http.https://github.com/.extraheader || echo "Header not found or failed to remove (expected if cleanup runs next)"
         shell: bash
 
   close_pull_request_job:
